id: P010407
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC462
  title: 'བོད་ཀྱི་གསོ་རིག་གི་གནས་བབ་གླེང་གཞིགས་དུས་ཀྱི་འབོད་སྒྲ། '
  author: ''
  volumes:
    466ce0b598f141f6b5184b6111bbee1f:
      image_group_id: I2PD20359
      title: ''
      volume_number: 1
      total_pages: 382
      base_file: v001.txt
